# Generated by Django 5.1.6 on 2025-03-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_certificates_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-end_date', '-start_date'], 'verbose_name_plural': 'Project'},
        ),
    ]
