# Generated by Django 5.1.6 on 2025-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='responsibilities',
            field=models.JSONField(default=list),
        ),
    ]
