# Generated by Django 5.1.6 on 2025-03-25 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_experience_responsibilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.AddField(
            model_name='project',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='resume.education'),
        ),
    ]
