# Generated by Django 5.1.6 on 2025-04-04 15:39

import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_personalinformation_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=resume.models.project_upload_path),
        ),
    ]
